  restaurants: [
    { id:1, name:"Napoli Fire", emoji:"🍕", bg:"#2a1f15", rating:4.8, time:"22–35 min", fee:"$1.99", category:"🍕 Pizza", badge:"", tags:["Wood-fired","Neapolitan","Italian","Pizza"], menu:[
      {id:101,name:"Margherita",desc:"San Marzano, fior di latte, basil",price:14.99,emoji:"🍕"},
      {id:102,name:"Diavola",desc:"Spicy salami, chili oil, olives",price:16.99,emoji:"🌶️"},
      {id:103,name:"Quattro Formaggi",desc:"Four cheese blend, honey drizzle",price:17.49,emoji:"🧀"},
      {id:104,name:"Prosciutto & Rocket",desc:"Cured ham, peppery rocket leaves",price:18.99,emoji:"🥗"},
      {id:105,name:"BBQ Chicken Pizza",desc:"Smoky BBQ base, mozzarella, jalapeno",price:16.49,emoji:"🍕"},
      {id:106,name:"Garlic Bread (x4)",desc:"Toasted, herb butter, parmesan",price:6.99,emoji:"🧄"},
    ]},
    { id:2, name:"Omakase Express", emoji:"🍣", bg:"#151f2a", rating:4.9, time:"30–45 min", fee:"$2.49", category:"🍣 Sushi", badge:"TOP RATED", tags:["Japanese","Fresh","Omakase","Sushi"], menu:[
      {id:201,name:"Salmon Nigiri (x2)",desc:"Atlantic salmon, sushi rice",price:8.99,emoji:"🐟"},
      {id:202,name:"Dragon Roll",desc:"Avocado, crab, eel sauce",price:15.49,emoji:"🍱"},
      {id:203,name:"Spicy Tuna Roll",desc:"Sriracha mayo, cucumber",price:13.99,emoji:"🔥"},
      {id:204,name:"Edamame",desc:"Sea salt, lemon zest",price:5.49,emoji:"🫘"},
      {id:205,name:"Rainbow Roll",desc:"Assorted fish, avocado, tobiko",price:17.99,emoji:"🌈"},
      {id:206,name:"Miso Soup",desc:"Tofu, wakame, green onion",price:3.99,emoji:"🍵"},
    ]},
    { id:3, name:"Taco Loco", emoji:"🌮", bg:"#1e1a10", rating:4.6, time:"15–25 min", fee:"Free", category:"🌮 Tacos", badge:"FAST", tags:["Mexican","Street food","Spicy","Tacos"], menu:[
      {id:301,name:"Al Pastor (x3)",desc:"Marinated pork, pineapple, cilantro",price:11.99,emoji:"🌮"},
      {id:302,name:"Birria Tacos (x2)",desc:"Braised beef, consomme dip",price:13.99,emoji:"🥩"},
      {id:303,name:"Guacamole & Chips",desc:"Fresh avocado, lime, jalapeno",price:7.49,emoji:"🥑"},
      {id:304,name:"Horchata (L)",desc:"Rice milk, cinnamon, vanilla",price:4.99,emoji:"🥛"},
      {id:305,name:"Nachos Supreme",desc:"Cheese, jalapeno, sour cream, salsa",price:9.99,emoji:"🫔"},
      {id:306,name:"Churros (x4)",desc:"Cinnamon sugar, chocolate dip",price:6.49,emoji:"🍩"},
    ]},
    { id:4, name:"Stack House", emoji:"🍔", bg:"#1f1515", rating:4.7, time:"20–30 min", fee:"$0.99", category:"🍔 Burgers", badge:"", tags:["Smash burgers","American","Loaded","Junk"], menu:[
      {id:401,name:"Classic Smash",desc:"Double patty, American cheese, pickles",price:12.99,emoji:"🍔"},
      {id:402,name:"BBQ Bacon Stack",desc:"Smoked bacon, BBQ sauce, onion rings",price:15.99,emoji:"🥓"},
      {id:403,name:"Crispy Fries",desc:"Sea salt, house seasoning",price:4.99,emoji:"🍟"},
      {id:404,name:"Vanilla Shake",desc:"Thick and creamy, 500ml",price:6.99,emoji:"🥤"},
      {id:405,name:"Chicken Burger",desc:"Crispy fried chicken, coleslaw, pickles",price:13.49,emoji:"🍔"},
      {id:406,name:"Loaded Cheese Fries",desc:"Nacho cheese, bacon bits, jalapenos",price:7.99,emoji:"🍟"},
      {id:407,name:"Onion Rings (x8)",desc:"Beer-battered, ranch dip",price:5.49,emoji:"🧅"},
    ]},
    { id:5, name:"Green Bowl Co.", emoji:"🥗", bg:"#121f15", rating:4.5, time:"18–28 min", fee:"Free", category:"🥗 Healthy", badge:"NEW", tags:["Vegan","Organic","Low-cal","Healthy"], menu:[
      {id:501,name:"Power Bowl",desc:"Quinoa, kale, chickpeas, tahini",price:13.49,emoji:"🥗"},
      {id:502,name:"Acai Bowl",desc:"Granola, fresh berries, honey",price:10.99,emoji:"🫐"},
      {id:503,name:"Green Detox Juice",desc:"Spinach, apple, ginger, lemon",price:6.49,emoji:"🥬"},
      {id:504,name:"Avocado Toast",desc:"Sourdough, chili flakes, seeds",price:9.99,emoji:"🥑"},
    ]},
    { id:6, name:"Ramen Underground", emoji:"🍜", bg:"#1a1220", rating:4.8, time:"25–40 min", fee:"$1.49", category:"🍜 Noodles", badge:"", tags:["Japanese","Broth","Cozy","Noodles"], menu:[
      {id:601,name:"Tonkotsu Ramen",desc:"Pork broth, chashu, soft egg",price:16.99,emoji:"🍜"},
      {id:602,name:"Spicy Miso Ramen",desc:"Red miso, corn, butter, tofu",price:15.49,emoji:"🌶️"},
      {id:603,name:"Gyoza (x6)",desc:"Pan-fried, dipping sauce",price:8.99,emoji:"🥟"},
      {id:604,name:"Matcha Latte",desc:"Ceremonial grade, oat milk",price:5.99,emoji:"🍵"},
      {id:605,name:"Tantanmen Ramen",desc:"Sesame broth, minced pork, bok choy, chili oil",price:16.49,emoji:"🍜"},
    ]},
    { id:7, name:"Spice Garden", emoji:"🍛", bg:"#1f1510", rating:4.6, time:"30–45 min", fee:"$1.99", category:"🍛 Indian", badge:"", tags:["Indian","Curry","Vegetarian","Paneer"], menu:[
      {id:701,name:"Butter Chicken",desc:"Creamy tomato-butter sauce, basmati rice",price:15.99,emoji:"🍛"},
      {id:702,name:"Paneer Tikka",desc:"Spiced cottage cheese, mint chutney",price:13.49,emoji:"🧀"},
      {id:703,name:"Garlic Naan (x3)",desc:"Buttery, clay oven baked",price:5.99,emoji:"🫓"},
      {id:704,name:"Mango Lassi",desc:"Chilled yogurt, ripe mango",price:4.99,emoji:"🥭"},
      {id:705,name:"Dal Makhani",desc:"Slow-cooked black lentils, cream, butter",price:11.99,emoji:"🍲"},
      {id:706,name:"Veg Biryani",desc:"Saffron rice, whole spices, raita",price:13.99,emoji:"🍚"},
      {id:707,name:"Palak Paneer",desc:"Spinach gravy, fresh cottage cheese",price:12.49,emoji:"🌿"},
      {id:708,name:"Samosa (x4)",desc:"Crispy pastry, spiced potato-pea filling",price:6.99,emoji:"🥟"},
    ]},
    { id:8, name:"Mughal Darbar", emoji:"👑", bg:"#2a1500", rating:4.9, time:"35–50 min", fee:"$2.99", category:"🍛 Indian", badge:"TOP RATED", tags:["Mughlai","Biryani","Non-veg","Indian"], menu:[
      {id:801,name:"Chicken Biryani",desc:"Slow dum-cooked, saffron, caramelized onions",price:17.99,emoji:"🍚"},
      {id:802,name:"Mutton Rogan Josh",desc:"Kashmiri slow-braised lamb, whole spices",price:19.99,emoji:"🥩"},
      {id:803,name:"Tandoori Chicken Half",desc:"Charcoal-smoked, yogurt-spice marinade",price:14.99,emoji:"🍗"},
      {id:804,name:"Seekh Kebab (x4)",desc:"Minced mutton on skewers, coal-grilled",price:13.49,emoji:"🍢"},
      {id:805,name:"Shahi Paneer",desc:"Rich cashew-cream gravy, cardamom",price:13.99,emoji:"🧀"},
      {id:806,name:"Peshwari Naan",desc:"Stuffed with coconut, almonds and raisins",price:3.99,emoji:"🫓"},
      {id:807,name:"Firni",desc:"Rose-flavored rice pudding, pistachios",price:5.99,emoji:"🍮"},
      {id:808,name:"Rooh Afza Sharbat",desc:"Chilled rose syrup, milk, basil seeds",price:3.99,emoji:"🌹"},
    ]},
    { id:9, name:"South Indian Express", emoji:"🥘", bg:"#0f1f10", rating:4.7, time:"20–35 min", fee:"$1.49", category:"🍛 Indian", badge:"FAST", tags:["South Indian","Dosa","Idli","Vegan"], menu:[
      {id:901,name:"Masala Dosa",desc:"Crispy fermented crepe, spiced potato, chutneys",price:10.99,emoji:"🥞"},
      {id:902,name:"Idli (x4) with Sambar",desc:"Steamed rice cakes, lentil-vegetable stew",price:8.99,emoji:"🍚"},
      {id:903,name:"Medu Vada (x3)",desc:"Crispy lentil doughnuts, coconut chutney",price:7.49,emoji:"🍩"},
      {id:904,name:"Chettinad Chicken Curry",desc:"Bold spices, kalpasi, stone flower",price:15.49,emoji:"🍛"},
      {id:905,name:"Uttapam",desc:"Thick rice pancake, onion-tomato topping",price:9.49,emoji:"🥞"},
      {id:906,name:"Filter Coffee",desc:"Strong decoction, frothed milk, hot",price:2.99,emoji:"☕"},
      {id:907,name:"Payasam",desc:"Sweet vermicelli in jaggery-coconut milk",price:5.49,emoji:"🍮"},
    ]},
    { id:10, name:"Chaat Corner", emoji:"🌶️", bg:"#1f100a", rating:4.8, time:"15–25 min", fee:"Free", category:"🍛 Indian", badge:"FAST", tags:["Street Food","Chaat","Snacks","Indian"], menu:[
      {id:1001,name:"Pani Puri (x6)",desc:"Hollow semolina shells, spiced tamarind water",price:6.99,emoji:"🟡"},
      {id:1002,name:"Bhel Puri",desc:"Puffed rice, sev, onions, tangy chutney",price:7.49,emoji:"🥗"},
      {id:1003,name:"Aloo Tikki Chaat",desc:"Crispy potato patties, curd, chutneys",price:8.49,emoji:"🟠"},
      {id:1004,name:"Dahi Papdi Chaat",desc:"Crispy papdis, creamy yogurt, tamarind, sev",price:8.99,emoji:"🍽️"},
      {id:1005,name:"Raj Kachori",desc:"Giant shell, sprouts, chutney, pomegranate",price:7.99,emoji:"🟤"},
      {id:1006,name:"Masala Chai",desc:"Ginger-cardamom spiced tea, full milk",price:2.49,emoji:"☕"},
      {id:1007,name:"Kulfi Malai",desc:"Traditional Indian ice cream, saffron",price:4.49,emoji:"🍦"},
      {id:1008,name:"Samosa Chaat",desc:"Crushed samosa, chole, chutneys, onion",price:9.49,emoji:"🥟"},
    ]},
    { id:11, name:"Punjabi Dhaba", emoji:"🌾", bg:"#1a1200", rating:4.7, time:"25–40 min", fee:"$1.99", category:"🍛 Indian", badge:"", tags:["Punjabi","Dhaba","Rotis","Hearty"], menu:[
      {id:1101,name:"Sarson Da Saag + Makki Roti",desc:"Mustard greens curry, corn flatbread, white butter",price:12.99,emoji:"🌿"},
      {id:1102,name:"Chole Bhature",desc:"Spiced chickpea curry, deep-fried puffed bread",price:11.49,emoji:"🫓"},
      {id:1103,name:"Amritsari Kulcha (x2)",desc:"Stuffed flatbread, chole, pickle",price:9.99,emoji:"🥯"},
      {id:1104,name:"Lassi Sweet or Salted",desc:"Thick churned yogurt drink, 400ml",price:4.49,emoji:"🥛"},
      {id:1105,name:"Aloo Paratha (x2)",desc:"Spiced potato stuffed bread, butter, curd",price:8.99,emoji:"🫓"},
      {id:1106,name:"Rajma Chawal",desc:"Kidney bean curry, steamed basmati rice",price:10.49,emoji:"🫘"},
      {id:1107,name:"Pindi Chole",desc:"Dry spiced chickpeas, ginger, pomegranate",price:11.49,emoji:"🫘"},
      {id:1108,name:"Gulab Jamun (x4)",desc:"Soft milk dumplings in rose sugar syrup",price:5.49,emoji:"🟤"},
    ]},
    { id:12, name:"Hyderabadi Kitchen", emoji:"🍖", bg:"#200a00", rating:4.9, time:"40–55 min", fee:"$2.49", category:"🍛 Indian", badge:"TOP RATED", tags:["Hyderabadi","Dum Biryani","Halal","Rich"], menu:[
      {id:1201,name:"Dum Gosht Biryani",desc:"Slow-cooked mutton, saffron, kewra, fried onions",price:21.99,emoji:"🍚"},
      {id:1202,name:"Chicken Dum Biryani",desc:"Dum-cooked chicken, aged basmati",price:17.99,emoji:"🍚"},
      {id:1203,name:"Haleem",desc:"Slow-cooked wheat, mutton and spices porridge",price:14.49,emoji:"🍲"},
      {id:1204,name:"Pathar Ka Gosht",desc:"Stone-roasted tenderized mutton, spice rub",price:18.99,emoji:"🥩"},
      {id:1205,name:"Double Ka Meetha",desc:"Bread pudding, cream, dry fruits, saffron",price:6.99,emoji:"🍮"},
      {id:1206,name:"Mirchi Ka Salan",desc:"Green chilli curry, peanut-sesame gravy",price:8.49,emoji:"🌶️"},
      {id:1207,name:"Irani Chai",desc:"Hyderabadi-style tea with sweetened milk",price:2.99,emoji:"☕"},
      {id:1208,name:"Osmania Biscuits (x6)",desc:"Buttery Irani cafe-style tea biscuits",price:3.99,emoji:"🍪"},
    ]},
    { id:13, name:"Mumbai Street Bites", emoji:"🏙️", bg:"#100a20", rating:4.7, time:"15–25 min", fee:"Free", category:"🍛 Indian", badge:"FAST", tags:["Mumbai","Vada Pav","Pav Bhaji","Street"], menu:[
      {id:1301,name:"Vada Pav",desc:"Spiced potato fritter in bread roll, chutneys",price:4.99,emoji:"🍔"},
      {id:1302,name:"Pav Bhaji",desc:"Spiced vegetable mash, buttery dinner rolls",price:9.99,emoji:"🍛"},
      {id:1303,name:"Misal Pav",desc:"Sprout curry, farsan toppings, bread rolls",price:10.49,emoji:"🌶️"},
      {id:1304,name:"Mumbai Sandwich",desc:"Butter, veggies, green chutney, cheese, grilled",price:7.99,emoji:"🥪"},
      {id:1305,name:"Keema Pav",desc:"Spiced minced mutton, buttered rolls",price:11.99,emoji:"🍖"},
      {id:1306,name:"Bhajiya Platter",desc:"Assorted fried fritters - onion, potato, chilli",price:7.49,emoji:"🍤"},
      {id:1307,name:"Cutting Chai (x2)",desc:"Half-cup strong Mumbai street tea",price:2.99,emoji:"☕"},
      {id:1308,name:"Shrikhand",desc:"Strained sweet yogurt, saffron, cardamom",price:5.49,emoji:"🍮"},
    ]},
    { id:14, name:"KrunchBox", emoji:"🍟", bg:"#1f1000", rating:4.5, time:"12–20 min", fee:"Free", category:"🍔 Burgers", badge:"FAST", tags:["Junk Food","Fried","Fast Food","Crispy"], menu:[
      {id:1401,name:"Mega Loaded Fries",desc:"Cheese sauce, bacon, jalapeno, sour cream",price:8.99,emoji:"🍟"},
      {id:1402,name:"Chicken Popcorn Box",desc:"Bite-sized crispy fried chicken pieces",price:9.49,emoji:"🍗"},
      {id:1403,name:"Double Cheeseburger",desc:"Two beef patties, double cheese, pickles",price:11.99,emoji:"🍔"},
      {id:1404,name:"Mozzarella Sticks (x6)",desc:"Gooey mozzarella, golden fried, marinara dip",price:7.99,emoji:"🧀"},
      {id:1405,name:"Hot Dog Loaded",desc:"Beef frank, cheese, chili, relish",price:8.49,emoji:"🌭"},
      {id:1406,name:"Fried Chicken Bucket (x8)",desc:"Original crispy recipe chicken pieces",price:19.99,emoji:"🍗"},
      {id:1407,name:"Corn Dog (x3)",desc:"Golden battered sausage on a stick",price:6.99,emoji:"🌽"},
      {id:1408,name:"Chocolate Milkshake",desc:"Thick, rich chocolate, whipped cream",price:5.99,emoji:"🥤"},
    ]},
    { id:15, name:"Pizza Bomb", emoji:"💣", bg:"#250010", rating:4.6, time:"20–35 min", fee:"$1.49", category:"🍕 Pizza", badge:"NEW", tags:["Pizza","Stuffed Crust","Junk","Cheesy"], menu:[
      {id:1501,name:"Stuffed Crust Pepperoni",desc:"Cheese-stuffed crust, pepperoni, extra mozzarella",price:18.99,emoji:"🍕"},
      {id:1502,name:"Loaded Meat Feast",desc:"Pepperoni, bacon, sausage, meatballs, BBQ base",price:21.99,emoji:"🥩"},
      {id:1503,name:"Cheese Burst Margherita",desc:"Double cheese, cheese burst base, basil",price:17.49,emoji:"🧀"},
      {id:1504,name:"Buffalo Chicken Pizza",desc:"Buffalo sauce, chicken, blue cheese, celery",price:19.49,emoji:"🌶️"},
      {id:1505,name:"Garlic Parmesan Wings (x8)",desc:"Crispy wings tossed in garlic-parmesan butter",price:12.99,emoji:"🍗"},
      {id:1506,name:"Brownie and Ice Cream",desc:"Warm chocolate brownie, vanilla scoop",price:7.99,emoji:"🍫"},
    ]},
    { id:16, name:"Fry Nation", emoji:"🥔", bg:"#1a0f00", rating:4.4, time:"10–18 min", fee:"Free", category:"🍔 Burgers", badge:"FAST", tags:["Fries","Snacks","Junk","Loaded"], menu:[
      {id:1601,name:"Poutine Classic",desc:"Fries, cheese curds, rich brown gravy",price:9.99,emoji:"🍟"},
      {id:1602,name:"Masala Fries",desc:"Fries tossed with chaat masala, chilli, lime",price:6.49,emoji:"🌶️"},
      {id:1603,name:"Waffle Fries + Dips (x3)",desc:"Crispy waffle cut, BBQ, ranch, cheese",price:7.99,emoji:"🍟"},
      {id:1604,name:"Dirty Fries",desc:"Fries, pulled pork, cheese, hot sauce",price:11.99,emoji:"🥩"},
      {id:1605,name:"Curly Fries",desc:"Seasoned curly cut, ketchup and mayo",price:5.49,emoji:"🍟"},
      {id:1606,name:"Slushie Strawberry",desc:"Frozen slushed ice, strawberry syrup",price:3.99,emoji:"🧃"},
    ]},
    { id:17, name:"Wok and Roll", emoji:"🥡", bg:"#1f102a", rating:4.7, time:"20–35 min", fee:"$1.49", category:"🥡 Asian", badge:"", tags:["Chinese","Dim Sum","Wok","Family"], menu:[
      {id:1701,name:"Kung Pao Chicken",desc:"Spiced chicken, peanuts, chili",price:14.49,emoji:"🍗"},
      {id:1702,name:"Dim Sum Platter",desc:"Pork dumplings, shrimp har gow",price:12.99,emoji:"🥟"},
      {id:1703,name:"Sweet and Sour Pork",desc:"Crispy pork, peppers, pineapple",price:13.99,emoji:"🥩"},
      {id:1704,name:"Peking Duck Bao",desc:"Steamed buns, hoisin, cucumber",price:11.49,emoji:"🥖"},
      {id:1705,name:"Egg Fried Rice",desc:"Wok-tossed rice, egg, spring onion, soy",price:10.49,emoji:"🍚"},
      {id:1706,name:"Spring Roll Basket (x6)",desc:"Crispy vegetable rolls, sweet chili sauce",price:8.49,emoji:"🥢"},
    ]},
    { id:18, name:"The Kebab Istana", emoji:"🍢", bg:"#2a2215", rating:4.8, time:"25–40 min", fee:"$2.99", category:"🍢 Kebab", badge:"TOP RATED", tags:["Middle Eastern","Halal","Grilled","Kebab"], menu:[
      {id:1801,name:"Chicken Shawarma",desc:"Spiced chicken, garlic whip, pickles",price:12.49,emoji:"🌯"},
      {id:1802,name:"Hummus and Pita",desc:"Creamy chickpea puree, warm flatbread",price:8.99,emoji:"🫓"},
      {id:1803,name:"Lamb Kofta",desc:"Minced skewers, saffron rice",price:15.99,emoji:"🥩"},
      {id:1804,name:"Falafel Wrap",desc:"Crispy herb fritters, tahini sauce",price:10.99,emoji:"🥙"},
      {id:1805,name:"Baklava (x4)",desc:"Filo pastry, pistachios, honey syrup",price:7.99,emoji:"🍯"},
    ]},
    { id:19, name:"Le Bistro", emoji:"🥖", bg:"#151b2a", rating:4.9, time:"30–50 min", fee:"$3.99", category:"🧁 Desserts", badge:"PREMIUM", tags:["French","Fine Dining","Gourmet"], menu:[
      {id:1901,name:"Coq au Vin",desc:"Braised chicken, red wine, mushrooms",price:24.99,emoji:"🍗"},
      {id:1902,name:"French Onion Soup",desc:"Beef broth, Gruyere crouton",price:11.99,emoji:"🥣"},
      {id:1903,name:"Creme Brulee",desc:"Vanilla bean custard, caramelized sugar",price:9.49,emoji:"🍮"},
      {id:1904,name:"Macaron Gift Box",desc:"Assorted French macarons (x6)",price:14.99,emoji:"🧁"},
    ]},
    { id:20, name:"La Dolce Vita", emoji:"🍝", bg:"#251c1a", rating:4.7, time:"25–35 min", fee:"$1.99", category:"🍝 Italian", badge:"", tags:["Pasta","Italian","Romantic"], menu:[
      {id:2001,name:"Truffle Fettuccine",desc:"Creamy wild mushroom, truffle oil",price:19.99,emoji:"🍝"},
      {id:2002,name:"Lasagna Classica",desc:"Bolognese, bechamel, parmigiano",price:17.49,emoji:"🥘"},
      {id:2003,name:"Gnocchi Pesto",desc:"Potato pillows, basil pesto",price:15.99,emoji:"🍃"},
      {id:2004,name:"Classic Tiramisu",desc:"Mascarpone, espresso, ladyfingers",price:8.99,emoji:"🍰"},
      {id:2005,name:"Carbonara Classica",desc:"Guanciale, egg yolk, Pecorino, black pepper",price:17.99,emoji:"🍝"},
      {id:2006,name:"Panna Cotta",desc:"Vanilla bean cream, strawberry coulis",price:6.99,emoji:"🍮"},
    ]},
    { id:21, name:"Coco Loco", emoji:"🥥", bg:"#10251f", rating:4.6, time:"10–20 min", fee:"Free", category:"🥤 Drinks", badge:"FAST", tags:["Smoothies","Juices","Cold drinks"], menu:[
      {id:2101,name:"Pure Coconut Water",desc:"Fresh young coconut, served cold",price:5.99,emoji:"🥥"},
      {id:2102,name:"Acai Superfood Smoothie",desc:"Acai, banana, almond milk, chia",price:7.99,emoji:"🥤"},
      {id:2103,name:"Iced Matcha Coconut",desc:"Ceremonial matcha, sweet coconut milk",price:6.99,emoji:"🍵"},
      {id:2104,name:"Tropical Dragon Punch",desc:"Dragonfruit, mango, passionfruit",price:7.49,emoji:"🍹"},
    ]},
    { id:22, name:"Steakhouse 72", emoji:"🥩", bg:"#2d1616", rating:4.9, time:"35–50 min", fee:"$4.99", category:"🍔 Burgers", badge:"PREMIUM", tags:["Steaks","Premium","Grill"], menu:[
      {id:2201,name:"Ribeye Steak 400g",desc:"USDA Prime, garlic butter, asparagus",price:34.99,emoji:"🥩"},
      {id:2202,name:"Truffle Mac and Cheese",desc:"Four-cheese blend, white truffle oil",price:11.99,emoji:"🧀"},
      {id:2203,name:"Wagyu Smash Burger",desc:"Double wagyu patty, truffle mayo",price:18.99,emoji:"🍔"},
      {id:2204,name:"Chocolate Souffle",desc:"Warm baked souffle, vanilla bean cream",price:10.99,emoji:"🧁"},
    ]},
    { id:23, name:"Seoul Bites", emoji:"🇰🇷", bg:"#0a0f20", rating:4.8, time:"25–40 min", fee:"$1.99", category:"🥡 Asian", badge:"NEW", tags:["Korean","BBQ","Fried Chicken","Spicy"], menu:[
      {id:2301,name:"Korean Fried Chicken (x6)",desc:"Double-fried, sweet soy glaze or spicy sauce",price:16.99,emoji:"🍗"},
      {id:2302,name:"Bibimbap Bowl",desc:"Steamed rice, veggies, gochujang, fried egg",price:14.49,emoji:"🥘"},
      {id:2303,name:"Tteokbokki",desc:"Spicy rice cakes, fish cake, gochujang broth",price:11.99,emoji:"🔴"},
      {id:2304,name:"Japchae",desc:"Glass noodles, sauteed veggies, sesame",price:12.49,emoji:"🍜"},
      {id:2305,name:"Sundubu Jjigae",desc:"Soft tofu stew, pork, egg, spicy broth",price:13.99,emoji:"🍲"},
      {id:2306,name:"Hotteok (x3)",desc:"Sweet filled Korean pancakes, brown sugar",price:6.49,emoji:"🥞"},
    ]},
    { id:24, name:"Bangkok Street", emoji:"🇹🇭", bg:"#0a2010", rating:4.7, time:"20–35 min", fee:"$1.49", category:"🥡 Asian", badge:"", tags:["Thai","Noodles","Curry","Spicy"], menu:[
      {id:2401,name:"Pad Thai",desc:"Stir-fried rice noodles, shrimp, peanuts, tamarind",price:13.99,emoji:"🍜"},
      {id:2402,name:"Green Curry Chicken",desc:"Coconut milk, Thai basil, kaffir lime",price:14.49,emoji:"🍛"},
      {id:2403,name:"Tom Yum Soup",desc:"Hot and sour lemongrass, mushroom, prawn",price:10.99,emoji:"🍲"},
      {id:2404,name:"Mango Sticky Rice",desc:"Jasmine sticky rice, fresh mango, coconut cream",price:7.99,emoji:"🥭"},
      {id:2405,name:"Som Tam Papaya Salad",desc:"Green papaya, chilli, lime, fish sauce, peanuts",price:9.49,emoji:"🥗"},
      {id:2406,name:"Thai Iced Tea",desc:"Strong brewed tea, condensed milk, ice",price:4.49,emoji:"🍵"},
      {id:2407,name:"Massaman Curry",desc:"Rich peanut curry, potato, tender beef",price:15.49,emoji:"🍛"},
    ]},
    { id:25, name:"Wing Zone", emoji:"🔥", bg:"#200500", rating:4.6, time:"18–28 min", fee:"$0.99", category:"🍔 Burgers", badge:"", tags:["Wings","Junk","American","Spicy"], menu:[
      {id:2501,name:"Buffalo Wings (x12)",desc:"Classic buffalo sauce, celery, blue cheese dip",price:17.99,emoji:"🍗"},
      {id:2502,name:"Honey Garlic Wings (x8)",desc:"Sweet sticky glaze, crispy fried",price:14.99,emoji:"🍯"},
      {id:2503,name:"Ghost Pepper Wings (x6)",desc:"Extreme heat, for the brave only",price:13.99,emoji:"🌶️"},
      {id:2504,name:"Loaded Nachos",desc:"Tortilla chips, cheese sauce, jalapenos, guac",price:10.99,emoji:"🫔"},
      {id:2505,name:"Mac and Cheese Bites (x8)",desc:"Fried macaroni cheese bites, ranch dip",price:8.99,emoji:"🧀"},
      {id:2506,name:"Root Beer Float",desc:"Frosty root beer, vanilla ice cream scoop",price:5.99,emoji:"🥤"},
    ]},
    { id:26, name:"Panda Palace", emoji:"🥢", bg:"#0f1515", rating:4.7, time:"25–40 min", fee:"$1.99", category:"🥡 Asian", badge:"", tags:["Chinese","Dim Sum","Wok","Family"], menu:[
      {id:2601,name:"Char Siu Pork Bao (x4)",desc:"Steamed BBQ pork buns, soft and fluffy",price:9.99,emoji:"🥖"},
      {id:2602,name:"Mapo Tofu",desc:"Silken tofu, minced pork, spicy bean paste",price:12.49,emoji:"🌶️"},
      {id:2603,name:"Peking Duck Pancakes (x8)",desc:"Crispy skin duck, cucumber, hoisin, pancakes",price:22.99,emoji:"🦆"},
      {id:2604,name:"Har Gow Dumplings (x4)",desc:"Translucent wrappers, plump shrimp filling",price:10.99,emoji:"🥟"},
      {id:2605,name:"Sesame Tofu Vegan",desc:"Crispy fried tofu, sesame glaze, bok choy",price:11.99,emoji:"🫘"},
    ]},
    { id:27, name:"Sundae Funday", emoji:"🍦", bg:"#1a0f25", rating:4.8, time:"10–20 min", fee:"Free", category:"🧁 Desserts", badge:"FAST", tags:["Ice Cream","Desserts","Waffles","Sweet"], menu:[
      {id:2701,name:"Belgian Waffle Sundae",desc:"Fresh waffle, 3 scoops ice cream, chocolate drizzle",price:12.99,emoji:"🧇"},
      {id:2702,name:"Banana Split",desc:"Banana, 3 scoops, hot fudge, nuts, cherry",price:10.99,emoji:"🍌"},
      {id:2703,name:"Nutella Crepe",desc:"Thin French crepe, Nutella, banana, whipped cream",price:9.49,emoji:"🥞"},
      {id:2704,name:"Brownie Fudge Sundae",desc:"Warm fudge brownie, caramel, ice cream, pecans",price:11.49,emoji:"🍫"},
      {id:2705,name:"Mango Kulfi Bar",desc:"Frozen Indian-style mango ice cream",price:4.99,emoji:"🥭"},
      {id:2706,name:"Cookie Dough Shake",desc:"Thick milkshake, raw cookie dough chunks",price:8.99,emoji:"🍪"},
      {id:2707,name:"Cinnamon Churros + Dip",desc:"Fresh fried churros, Nutella and caramel",price:7.99,emoji:"🍩"},
    ]},
    { id:28, name:"Bubble Tea House", emoji:"🧋", bg:"#1a0a2a", rating:4.7, time:"10–20 min", fee:"Free", category:"🥤 Drinks", badge:"NEW", tags:["Bubble Tea","Boba","Taiwanese","Cold"], menu:[
      {id:2801,name:"Classic Milk Tea + Boba",desc:"Black tea, creamy milk, chewy boba pearls",price:6.49,emoji:"🧋"},
      {id:2802,name:"Taro Latte Hot or Cold",desc:"Purple taro root, creamy milk, boba",price:6.99,emoji:"🟣"},
      {id:2803,name:"Mango Passion Fruit Tea",desc:"Fresh mango, passion fruit jelly, green tea",price:6.99,emoji:"🥭"},
      {id:2804,name:"Brown Sugar Tiger Milk Tea",desc:"Tiger stripe caramel, fresh milk, boba",price:7.49,emoji:"🐯"},
      {id:2805,name:"Matcha Cheese Foam",desc:"Iced matcha, salted cream cheese foam",price:7.99,emoji:"🍵"},
      {id:2806,name:"Strawberry Yakult",desc:"Yakult probiotic, strawberry, aloe vera, ice",price:5.99,emoji:"🍓"},
      {id:2807,name:"Lychee Iced Tea",desc:"Brewed oolong, lychee popping pearls, mint",price:6.49,emoji:"🍹"},
    ]},
    { id:29, name:"Doner Delights", emoji:"🌯", bg:"#252015", rating:4.6, time:"15–25 min", fee:"Free", category:"🍢 Kebab", badge:"FAST", tags:["Turkish","Doner","Wrap","Halal"], menu:[
      {id:2901,name:"Chicken Doner Wrap",desc:"Marinated chicken strips, garlic sauce, salad",price:11.49,emoji:"🌯"},
      {id:2902,name:"Mixed Meat Doner Box",desc:"Chicken and lamb, fries, salad, sauces",price:14.99,emoji:"🥩"},
      {id:2903,name:"Iskender Kebab",desc:"Sliced doner on pide, tomato-butter sauce, yogurt",price:16.49,emoji:"🍢"},
      {id:2904,name:"Lahmacun (x2)",desc:"Turkish minced meat flatbread pizza",price:8.99,emoji:"🍕"},
      {id:2905,name:"Ayran",desc:"Chilled salted yogurt drink, frothy",price:2.99,emoji:"🥛"},
    ]},
    { id:30, name:"Shawarma Street", emoji:"🫔", bg:"#200f00", rating:4.7, time:"15–25 min", fee:"Free", category:"🍢 Kebab", badge:"FAST", tags:["Shawarma","Lebanese","Halal","Wrap"], menu:[
      {id:3001,name:"Chicken Shawarma Plate",desc:"Rotisserie chicken, garlic sauce, fries, salad",price:13.99,emoji:"🍗"},
      {id:3002,name:"Beef Shawarma Wrap",desc:"Spiced beef, tahini, tomato, parsley, flatbread",price:12.49,emoji:"🌯"},
      {id:3003,name:"Mixed Grill Platter",desc:"Chicken and beef shawarma, grilled veggies, pita",price:18.99,emoji:"🍖"},
      {id:3004,name:"Fattoush Salad",desc:"Toasted pita, mixed greens, sumac dressing",price:7.99,emoji:"🥗"},
      {id:3005,name:"Knafeh",desc:"Warm cheese pastry, rose water syrup, pistachios",price:7.49,emoji:"🟡"},
      {id:3006,name:"Fresh Mint Lemonade",desc:"Cold-pressed lemon, fresh mint, sugar syrup",price:3.99,emoji:"🍋"},
    ]},
    { id:31, name:"Grill and Chill", emoji:"🏕️", bg:"#121f0f", rating:4.6, time:"25–40 min", fee:"$1.99", category:"🍔 Burgers", badge:"", tags:["BBQ","Smoky","American","Ribs"], menu:[
      {id:3101,name:"St. Louis Ribs Half Rack",desc:"Slow-smoked pork ribs, house BBQ rub, slaw",price:22.99,emoji:"🍖"},
      {id:3102,name:"Brisket Platter",desc:"12-hr smoked brisket, Texas toast, pickles",price:19.99,emoji:"🥩"},
      {id:3103,name:"BBQ Pulled Pork Sandwich",desc:"Slow-cooked pulled pork, brioche, slaw",price:13.49,emoji:"🥪"},
      {id:3104,name:"Smoked Mac and Cheese",desc:"Four-cheese, smoked in the pit, breadcrumb crust",price:9.99,emoji:"🧀"},
      {id:3105,name:"Corn on the Cob (x2)",desc:"Grilled, chipotle butter, cotija cheese",price:5.99,emoji:"🌽"},
      {id:3106,name:"Peach Cobbler",desc:"Warm baked peach cobbler, vanilla ice cream",price:7.99,emoji:"🍑"},
    ]},
    { id:32, name:"Coastal Catch", emoji:"🦞", bg:"#0a1520", rating:4.8, time:"30–45 min", fee:"$2.99", category:"🥡 Asian", badge:"", tags:["Seafood","Grilled","Fresh","Coastal"], menu:[
      {id:3201,name:"Fish and Chips",desc:"Beer-battered cod, mushy peas, tartar sauce",price:14.99,emoji:"🐟"},
      {id:3202,name:"Prawn Cocktail",desc:"King prawns, Marie Rose sauce, iceberg lettuce",price:11.49,emoji:"🦐"},
      {id:3203,name:"Grilled Salmon Steak",desc:"Lemon-herb salmon, seasonal greens, hollandaise",price:19.99,emoji:"🐠"},
      {id:3204,name:"Lobster Roll",desc:"Butter-poached lobster, brioche bun, chives",price:24.99,emoji:"🦞"},
      {id:3205,name:"Calamari Rings",desc:"Crispy fried squid, lemon aioli",price:10.99,emoji:"🦑"},
      {id:3206,name:"Clam Chowder Bowl",desc:"Creamy New England chowder, sourdough bowl",price:12.99,emoji:"🍲"},
    ]},
    { id:33, name:"Whisk and Crumb", emoji:"🧁", bg:"#1f1520", rating:4.9, time:"15–30 min", fee:"$0.99", category:"🧁 Desserts", badge:"TOP RATED", tags:["Bakery","Sweet","Artisan","Desserts"], menu:[
      {id:3301,name:"Chocolate Lava Cake",desc:"Warm dark chocolate, vanilla ice cream",price:9.99,emoji:"🍫"},
      {id:3302,name:"NY Cheesecake Slice",desc:"Biscuit base, berry compote",price:7.99,emoji:"🍰"},
      {id:3303,name:"Croissant Box (x4)",desc:"Flaky, butter laminated",price:11.99,emoji:"🥐"},
      {id:3304,name:"Cold Brew Float",desc:"Espresso, vanilla gelato",price:7.49,emoji:"☕"},
      {id:3305,name:"Strawberry Cheesecake",desc:"Fresh strawberry, creamy filling, graham base",price:8.49,emoji:"🍓"},
    ]},
    { id:34, name:"Wrap Republic", emoji:"🥙", bg:"#0f1a10", rating:4.5, time:"15–25 min", fee:"Free", category:"🍔 Burgers", badge:"FAST", tags:["Wraps","Grilled","Chicken","Healthy-ish"], menu:[
      {id:3401,name:"Grilled Chicken Wrap",desc:"Char-grilled chicken, lettuce, tomato, garlic mayo",price:11.49,emoji:"🥙"},
      {id:3402,name:"Paneer Tikka Wrap",desc:"Tandoori paneer, mint chutney, onion, pepper",price:10.99,emoji:"🌿"},
      {id:3403,name:"Spicy Prawn Wrap",desc:"Garlic butter prawns, sriracha slaw, avocado",price:13.99,emoji:"🦐"},
      {id:3404,name:"Breakfast Wrap",desc:"Egg, bacon, cheese, hash brown, ketchup",price:9.99,emoji:"🥚"},
      {id:3405,name:"Falafel and Hummus Wrap",desc:"Crispy falafel, creamy hummus, pickled cabbage",price:10.49,emoji:"🧆"},
    ]},
    { id:35, name:"Whispering Wok", emoji:"🍲", bg:"#10200f", rating:4.6, time:"22–35 min", fee:"$1.49", category:"🍜 Noodles", badge:"", tags:["Asian Fusion","Noodles","Rice","Healthy"], menu:[
      {id:3501,name:"Laksa Soup",desc:"Spicy coconut milk broth, rice noodles, prawns",price:14.99,emoji:"🍜"},
      {id:3502,name:"Hainanese Chicken Rice",desc:"Poached chicken, fragrant rice, ginger sauce",price:13.49,emoji:"🍚"},
      {id:3503,name:"Singapore Noodles",desc:"Rice vermicelli, curry powder, shrimp, egg",price:12.99,emoji:"🍜"},
      {id:3504,name:"Char Kway Teow",desc:"Flat rice noodles, wok-fried, dark soy, bean sprouts",price:13.99,emoji:"🥘"},
      {id:3505,name:"Teh Tarik",desc:"Malaysian pulled milk tea, frothy and sweet",price:3.99,emoji:"🍵"},
      {id:3506,name:"Ondeh Ondeh (x6)",desc:"Pandan rice balls with palm sugar filling",price:6.99,emoji:"🟢"},
    ]}
  ]
